### ISSUE TITLE
--access=public 옵션을 줄수는 없을까요?

### ISSUE THREAD

**Issue by stepanowon** [rocket-hangar/rocket-punch#4]
우선 훌륭한 유틸리티를 만들어주셔서  진심으로 감사드립니다.

실행해보니 이런 에러가 뜨네요. 
npm ERR! 402 Payment Required - ....  - You must sign up for private packages

오류의 원인을 찾아보니 npm publish 시에 --access=public 옵션을 주면 해결할 수 있는듯 한데 , rocket-punch에는 아직 그 기능이 없는건가요?

기능이 아직 없다면 추가해주면 정말 감사할듯 합니다.

**Comment by iamssen** [comment]
@stepanowon https://www.notion.so/ssen/Rocket-Punch-7db34cad1cb444bb945f1a4b9bc3cc8a#8d8f6519c8e44832b51abb60cab40804

`--access=public`은 현재는 `.package.json` 에 `publishConfig` 설정을 추가해서 처리할 수 있습니다.

에러 메세지가 "You must sign up..." 인걸 보니 `npm login` 을 하셨는지 먼저 확인하셔야 할 것 같습니다. `npm whoami` 를 쳐서 본인의 npm 계정 아이디가 나오면 로그인 된 것이니 확인해주세요.

**Comment by stepanowon** [comment]
네....제가 착각한거네요.. 잘됩니다. 감사합니다. 대신에 publishConfig 설정으로는 안되고 
npm run publish --access=public  과 같이 직접 주니 잘됩니다.

어쨌거나 좋은 유틸리티 만들어주셔서 감사해요.

**Comment by iamssen** [comment]
@stepanowon 앗??? `npm run publish --access=public` 으로 동작할 수 없는 구조라서... `publishConfig` 설정만 유지한채로 `npm run publish`를 해주실 수 있을까요? (예상과 다르게 동작하는 경우라서 확인해주시면 도움이 될 것 같습니다)

 `package` 같이 grouped 되지 않은 package는 기본 설정이 public 이라서 access 설정이 없는 경우 public으로 배포되게 되고, (`npm login` 만 되어 있어도 배포 가능)

`@group/package` 같은 grouped 된 package는 기본 설정이 private 이라서 access 설정이 없는 경우 private으로 배포되게 되는데 이 경우 npm 유료 계정이 아니면 에러가 날겁니다. (`npm login` 과 함께 `access=public` 설정이 되어 있어야만 무료 계정에서 배포 가능)

**Comment by stepanowon** [comment]
이거 테스트하느라고 유료계정으로 업그레이드해버렸습니다. 에러 메시지를 캡춰할 수가 없네요. 유료 계정에서 다시 free plan으로 내렸는데. 한달간은 유료 플랜 적용이 되나봅니다.

어쨌든 npm run publish 로 게시하면 private 으로 등록이 됩니다. npm run publish --access=public 으로 실행하면 public으로 등록되는것을 확인했습니다.

**Comment by iamssen** [comment]
@stepanowon 확인 감사합니다. 😊
